import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:recettas/services/purchase_categorizer.dart';

void main() {
  test('matches the Python categorizer on every real-data case', () {
    // Golden fixture generated by running categorizar.py
    // (normalize_item_name + categorize_item) over the real gastos.csv;
    // category is null where Python fell back to the generic 'Outros'.
    final cases = jsonDecode(
            File('test/fixtures/categorizer_cases.json')
                .readAsStringSync())
        as List<dynamic>;
    expect(cases, isNotEmpty);

    final mismatches = <String>[];
    for (final c in cases) {
      final item = c['item'] as String;
      final store = c['store'] as String?;
      final expected = c['category'] as String?;
      final actual = PurchaseCategorizer.categorize(item, store);
      if (actual != expected) {
        mismatches.add('"$item" (store: "$store"): '
            'expected $expected, got $actual');
      }
    }
    expect(mismatches, isEmpty,
        reason: 'Diverged from categorizar.py:\n${mismatches.join('\n')}');
  });

  test('quantity prefix is stripped before matching', () {
    expect(PurchaseCategorizer.categorize('2 Pizzas', null), 'Alimentacao');
  });

  test('accent-stripped second pass', () {
    // No accented rule for "pao frances", matches on the stripped pass.
    expect(
        PurchaseCategorizer.categorize('Pão Francês', null), 'Alimentacao');
  });

  test('store hints categorize unknown items', () {
    expect(PurchaseCategorizer.categorize('parafuso sextavado', 'Larissa Construcoes'),
        'Construcao');
    expect(PurchaseCategorizer.categorize('coisa qualquer', 'Plastilandia'),
        'Casa');
  });

  test('exact matches', () {
    expect(PurchaseCategorizer.categorize('?', null), 'Outros');
    expect(PurchaseCategorizer.categorize('Tatu', null), 'Lazer');
  });

  test('unmatched items return null instead of Outros', () {
    expect(PurchaseCategorizer.categorize('zzz coisa misteriosa', null),
        isNull);
    expect(PurchaseCategorizer.categorize('', null), isNull);
    expect(PurchaseCategorizer.categorize('   ', 'Assaí'), isNull);
  });

  test('nameKey matches accented user names to rule names', () {
    expect(PurchaseCategorizer.nameKey('Alimentação'),
        PurchaseCategorizer.nameKey('Alimentacao'));
    expect(PurchaseCategorizer.nameKey('SERVIÇOS'),
        PurchaseCategorizer.nameKey('Servicos'));
  });

  test('every rule category has a default color', () {
    // All categories the rules can produce must be creatable.
    final produced = <String>{
      for (final c in jsonDecode(
              File('test/fixtures/categorizer_cases.json')
                  .readAsStringSync()) as List<dynamic>)
        if (c['category'] != null) c['category'] as String,
    };
    for (final cat in produced) {
      expect(PurchaseCategorizer.categoryColors.containsKey(cat), isTrue,
          reason: 'Missing color for $cat');
    }
  });
}
