-- Seeds the shared exercise catalog (user_id null, same convention as the
-- rest of the hand-seeded rows) from the videos bundled at
-- assets/exercises/. muscle_group holds the Portuguese category name used
-- as the gallery's filter chips in gym_screen.dart, so it's written in
-- Portuguese here rather than translated at render time.
insert into public.exercises (name, name_pt, muscle_group, video_path) values
  ('Barbell Bent Over Row', 'Remada Curvada com Barra', 'Costas', 'assets/exercises/Barbell Bent Over Row.mp4'),
  ('Barbell Coan Deadlift', 'Levantamento Terra Coan com Barra', 'Glúteos', 'assets/exercises/Barbell Coan Deadlift.mp4'),
  ('Barbell Curl', 'Rosca Direta com Barra', 'Bíceps', 'assets/exercises/Barbell Curl.mp4'),
  ('Barbell Deadlift', 'Levantamento Terra com Barra', 'Glúteos', 'assets/exercises/Barbell Deadlift.mp4'),
  ('Barbell Floor Press', 'Supino no Chão com Barra', 'Peito', 'assets/exercises/Barbell Floor Press.mp4'),
  ('Barbell Front Raise', 'Elevação Frontal com Barra', 'Ombros', 'assets/exercises/Barbell Front Raise.mp4'),
  ('Barbell Front Squat Bodybuilding', 'Agachamento Frontal com Barra', 'Pernas', 'assets/exercises/Barbell Front Squat Bodybuilding.mp4'),
  ('Barbell High Bar Squat', 'Agachamento Barra Alta', 'Pernas', 'assets/exercises/Barbell High Bar Squat.mp4'),
  ('Barbell Hip Thrust', 'Elevação de Quadril com Barra', 'Glúteos', 'assets/exercises/Barbell Hip Thrust.mp4'),
  ('Barbell Low Bar Squat', 'Agachamento Barra Baixa', 'Pernas', 'assets/exercises/Barbell Low Bar Squat.mp4'),
  ('Barbell Overhead Press', 'Desenvolvimento com Barra', 'Ombros', 'assets/exercises/Barbell Overhead Press.mp4'),
  ('Barbell Romanian Deadlift', 'Levantamento Terra Romeno com Barra', 'Glúteos', 'assets/exercises/Barbell Romanian Deadlift.mp4'),
  ('Barbell Split Squat', 'Agachamento Búlgaro com Barra', 'Pernas', 'assets/exercises/Barbell Split Squat.mp4'),
  ('Barbell Squat', 'Agachamento com Barra', 'Pernas', 'assets/exercises/Barbell Squat.mp4'),
  ('Barbell Step Up', 'Subida no Step com Barra', 'Pernas', 'assets/exercises/Barbell Step Up.mp4'),
  ('Barbell Stiff Leg Deadlifts', 'Levantamento Terra Stiff com Barra', 'Glúteos', 'assets/exercises/Barbell Stiff Leg Deadlifts.mp4'),
  ('Barbell Sumo Deadlift', 'Levantamento Terra Sumô com Barra', 'Glúteos', 'assets/exercises/Barbell Sumo Deadlift.mp4'),
  ('Barbell Upright Row', 'Remada Alta com Barra', 'Ombros', 'assets/exercises/Barbell Upright Row.mp4'),
  ('Bodyweight Squat', 'Agachamento Livre', 'Pernas', 'assets/exercises/Bodyweight Squat.mp4'),
  ('Cable Archer Row', 'Remada Arqueiro no Cabo', 'Costas', 'assets/exercises/Cable Archer Row.mp4'),
  ('Cable Bar Romanian Deadlift', 'Levantamento Terra Romeno com Barra no Cabo', 'Glúteos', 'assets/exercises/Cable Bar Romanian Deadlift.mp4'),
  ('Cable Bar Skullcrusher', 'Tríceps Testa com Barra no Cabo', 'Tríceps', 'assets/exercises/Cable Bar Skullcrusher.mp4'),
  ('Cable Bar Staggered Romanian Deadlift', 'Levantamento Terra Romeno Unilateral com Barra no Cabo', 'Glúteos', 'assets/exercises/Cable Bar Staggered Romanian Deadlift.mp4'),
  ('Cable Belt Split Squat', 'Agachamento Búlgaro com Cinto no Cabo', 'Pernas', 'assets/exercises/Cable Belt Split Squat.mp4'),
  ('Cable Belt Squat', 'Agachamento com Cinto no Cabo', 'Pernas', 'assets/exercises/Cable Belt Squat.mp4'),
  ('Cable Bench Straight Leg Kickback', 'Coice na Polia Perna Estendida no Banco', 'Glúteos', 'assets/exercises/Cable Bench Straight Leg Kickback.mp4'),
  ('Cable Bent Over Bar Pullover', 'Pullover Curvado com Barra no Cabo', 'Costas', 'assets/exercises/Cable Bent Over Bar Pullover.mp4'),
  ('Cable Bent Over Single Arm Overhead Tricep Extension', 'Tríceps Testa Unilateral Curvado no Cabo', 'Tríceps', 'assets/exercises/Cable Bent Over Single Arm Overhead Tricep Extension.mp4'),
  ('Cable Calve Raise', 'Elevação de Panturrilha no Cabo', 'Panturrilha', 'assets/exercises/Cable Calve Raise.mp4'),
  ('Cable Goblet Squat', 'Agachamento Goblet no Cabo', 'Pernas', 'assets/exercises/Cable Goblet Squat.mp4'),
  ('Cable High Bayesian Curl', 'Rosca Bayesian Alta no Cabo', 'Bíceps', 'assets/exercises/Cable High Bayesian Curl.mp4'),
  ('Cable High Single Arm Reverse Bayesian Curl', 'Rosca Bayesian Inversa Unilateral Alta no Cabo', 'Bíceps', 'assets/exercises/Cable High Single Arm Reverse Bayesian Curl.mp4'),
  ('Cable Lat Prayer', 'Alongamento de Dorsal no Cabo (Lat Prayer)', 'Costas', 'assets/exercises/Cable Lat Prayer.mp4'),
  ('Cable Leaning Single Arm Skullover', 'Tríceps Testa e Pullover Unilateral Inclinado no Cabo', 'Tríceps', 'assets/exercises/Cable Leaning Single Arm Skullover.mp4'),
  ('Cable Low Single Arm Lateral Raise', 'Elevação Lateral Unilateral Baixa no Cabo', 'Ombros', 'assets/exercises/Cable Low Single Arm Lateral Raise.mp4'),
  ('Cable Pull Around', 'Puxada Circular no Cabo', 'Costas', 'assets/exercises/Cable Pull Around.mp4'),
  ('Cable Pull In', 'Puxada para Dentro no Cabo', 'Costas', 'assets/exercises/Cable Pull In.mp4'),
  ('Cable Pull Through', 'Pull Through no Cabo', 'Glúteos', 'assets/exercises/Cable Pull Through.mp4'),
  ('Cable Quadruped Hip Abduction', 'Abdução de Quadril em Quatro Apoios no Cabo', 'Glúteos', 'assets/exercises/Cable Quadruped Hip Abduction.mp4'),
  ('Cable Rope Hammer Curl', 'Rosca Martelo com Corda no Cabo', 'Bíceps', 'assets/exercises/Cable Rope Hammer Curl.mp4'),
  ('Cable Rope Overhead Tricep Extension', 'Tríceps Francês com Corda no Cabo', 'Tríceps', 'assets/exercises/Cable Rope Overhead Tricep Extension.mp4'),
  ('Cable Rope Pullover', 'Pullover com Corda no Cabo', 'Costas', 'assets/exercises/Cable Rope Pullover.mp4'),
  ('Cable Rope Pushdown', 'Tríceps Corda na Polia', 'Tríceps', 'assets/exercises/Cable Rope Pushdown.mp4'),
  ('Cable Rope Skullcrusher', 'Tríceps Testa com Corda no Cabo', 'Tríceps', 'assets/exercises/Cable Rope Skullcrusher.mp4'),
  ('Cable Row Bar Standing Row', 'Remada em Pé com Barra no Cabo', 'Costas', 'assets/exercises/Cable Row Bar Standing Row.mp4'),
  ('Cable Single Arm Cross Pushdown', 'Tríceps Cruzado Unilateral na Polia', 'Tríceps', 'assets/exercises/Cable Single Arm Cross Pushdown.mp4'),
  ('Cable Single Arm Hammer Curl', 'Rosca Martelo Unilateral no Cabo', 'Bíceps', 'assets/exercises/Cable Single Arm Hammer Curl.mp4'),
  ('Cable Single Arm Neutral Grip Row', 'Remada Unilateral Pegada Neutra no Cabo', 'Costas', 'assets/exercises/Cable Single Arm Neutral Grip Row.mp4'),
  ('Cable Single Arm Overhead Tricep Extension', 'Tríceps Francês Unilateral no Cabo', 'Tríceps', 'assets/exercises/Cable Single Arm Overhead Tricep Extension.mp4'),
  ('Cable Single Arm Pushdown', 'Tríceps Unilateral na Polia', 'Tríceps', 'assets/exercises/Cable Single Arm Pushdown.mp4'),
  ('Cable Single Arm Rope Pushdown', 'Tríceps Corda Unilateral na Polia', 'Tríceps', 'assets/exercises/Cable Single Arm Rope Pushdown.mp4'),
  ('Cable Single Leg Deadlift', 'Levantamento Terra Unilateral no Cabo', 'Glúteos', 'assets/exercises/Cable Single Leg Deadlift.mp4'),
  ('Cable Split Squat', 'Agachamento Búlgaro no Cabo', 'Pernas', 'assets/exercises/Cable Split Squat.mp4'),
  ('Cable Standing Glute Kickback', 'Coice na Polia em Pé no Cabo', 'Glúteos', 'assets/exercises/Cable Standing Glute Kickback.mp4'),
  ('Cable Standing Hip Abduction', 'Abdução de Quadril em Pé no Cabo', 'Glúteos', 'assets/exercises/Cable Standing Hip Abduction.mp4'),
  ('Cable Standing Hip Adduction', 'Adução de Quadril em Pé no Cabo', 'Glúteos', 'assets/exercises/Cable Standing Hip Adduction.mp4'),
  ('Cable Standing Leg Extension', 'Extensão de Perna em Pé no Cabo', 'Pernas', 'assets/exercises/Cable Standing Leg Extension.mp4'),
  ('Cable Standing Mid Kickback', 'Coice na Polia Médio em Pé no Cabo', 'Glúteos', 'assets/exercises/Cable Standing Mid Kickback.mp4'),
  ('Cable Standing Single Arm Cross Rear Delt Row', 'Remada Cruzada Unilateral para Deltoide Posterior no Cabo', 'Ombros', 'assets/exercises/Cable Standing Single Arm Cross Rear Delt Row.mp4'),
  ('Cable Standing Straight Leg Glute Kickback', 'Coice na Polia Perna Estendida em Pé no Cabo', 'Glúteos', 'assets/exercises/Cable Standing Straight Leg Glute Kickback.mp4'),
  ('Cable Standing Straight Leg Mid Kickback', 'Coice na Polia Médio Perna Estendida em Pé no Cabo', 'Glúteos', 'assets/exercises/Cable Standing Straight Leg Mid Kickback.mp4'),
  ('Cable Straight Arm Pull In', 'Puxada Braço Estendido no Cabo', 'Costas', 'assets/exercises/Cable Straight Arm Pull In.mp4'),
  ('Cable Supinating Row', 'Remada com Rotação Supinada no Cabo', 'Costas', 'assets/exercises/Cable Supinating Row.mp4'),
  ('Cable Twisting Curl', 'Rosca com Rotação no Cabo', 'Bíceps', 'assets/exercises/Cable Twisting Curl.mp4'),
  ('Cable Upright Row', 'Remada Alta no Cabo', 'Ombros', 'assets/exercises/Cable Upright Row.mp4'),
  ('Cable Zercher Good Morning', 'Bom Dia Zercher no Cabo', 'Glúteos', 'assets/exercises/Cable Zercher Good Morning.mp4'),
  ('Chin Ups', 'Barra Fixa Supinada', 'Costas', 'assets/exercises/Chin Ups.mp4'),
  ('Dumbbell Bench Press', 'Supino com Halteres', 'Peito', 'assets/exercises/Dumbbell Bench Press.mp4'),
  ('Dumbbell Bulgarian Split Squat', 'Agachamento Búlgaro com Halteres', 'Pernas', 'assets/exercises/Dumbbell Bulgarian Split Squat.mp4'),
  ('Dumbbell Chest Fly', 'Crucifixo com Halteres', 'Peito', 'assets/exercises/Dumbbell Chest Fly.mp4'),
  ('Dumbbell Concentration Curl', 'Rosca Concentrada com Halteres', 'Bíceps', 'assets/exercises/Dumbbell Concentration Curl.mp4'),
  ('Dumbbell Curl', 'Rosca Direta com Halteres', 'Bíceps', 'assets/exercises/Dumbbell Curl.mp4'),
  ('Dumbbell Forward Lunge', 'Avanço à Frente com Halteres', 'Pernas', 'assets/exercises/Dumbbell Forward Lunge.mp4'),
  ('Dumbbell Front Raise', 'Elevação Frontal com Halteres', 'Ombros', 'assets/exercises/Dumbbell Front Raise.mp4'),
  ('Dumbbell Full Lateral Raise', 'Elevação Lateral Completa com Halteres', 'Ombros', 'assets/exercises/Dumbbell Full Lateral Raise.mp4'),
  ('Dumbbell Glute Bridge', 'Ponte de Glúteo com Halteres', 'Glúteos', 'assets/exercises/Dumbbell Glute Bridge.mp4'),
  ('Dumbbell Goblet Squat', 'Agachamento Goblet com Halteres', 'Pernas', 'assets/exercises/Dumbbell Goblet Squat.mp4'),
  ('Dumbbell Guillotine Bench Press', 'Supino Guilhotina com Halteres', 'Peito', 'assets/exercises/Dumbbell Guillotine Bench Press.mp4'),
  ('Dumbbell Hammer Curl', 'Rosca Martelo com Halteres', 'Bíceps', 'assets/exercises/Dumbbell Hammer Curl.mp4'),
  ('Dumbbell Hip Thrust', 'Elevação de Quadril com Halteres', 'Glúteos', 'assets/exercises/Dumbbell Hip Thrust.mp4'),
  ('Dumbbell Internally Rotated Chest Fly', 'Crucifixo com Rotação Interna com Halteres', 'Peito', 'assets/exercises/Dumbbell Internally Rotated Chest Fly.mp4'),
  ('Dumbbell Lateral Raise', 'Elevação Lateral com Halteres', 'Ombros', 'assets/exercises/Dumbbell Lateral Raise.mp4'),
  ('Dumbbell Neutral Bench Press', 'Supino Pegada Neutra com Halteres', 'Peito', 'assets/exercises/Dumbbell Neutral Bench Press.mp4'),
  ('Dumbbell Neutral Seated Overhead Press', 'Desenvolvimento Sentado Pegada Neutra com Halteres', 'Ombros', 'assets/exercises/Dumbbell Neutral Seated Overhead Press.mp4'),
  ('Dumbbell Overhead Press', 'Desenvolvimento com Halteres', 'Ombros', 'assets/exercises/Dumbbell Overhead Press.mp4'),
  ('Dumbbell Push Press', 'Push Press com Halteres', 'Ombros', 'assets/exercises/Dumbbell Push Press.mp4'),
  ('Dumbbell Reverse Curl', 'Rosca Inversa com Halteres', 'Bíceps', 'assets/exercises/Dumbbell Reverse Curl.mp4'),
  ('Dumbbell Romanian Deadlift', 'Levantamento Terra Romeno com Halteres', 'Glúteos', 'assets/exercises/Dumbbell Romanian Deadlift.mp4'),
  ('Dumbbell Seated Overhead Press', 'Desenvolvimento Sentado com Halteres', 'Ombros', 'assets/exercises/Dumbbell Seated Overhead Press.mp4'),
  ('Dumbbell Single Arm Clean And Press', 'Clean and Press Unilateral com Halter', 'Corpo Inteiro', 'assets/exercises/Dumbbell Single Arm Clean And Press.mp4'),
  ('Elevated Pike Press', 'Pike Press Elevado', 'Ombros', 'assets/exercises/Elevated Pike Press.mp4'),
  ('Forward Lunges', 'Avanço à Frente', 'Pernas', 'assets/exercises/Forward Lunges.mp4'),
  ('Jump Squats', 'Agachamento com Salto', 'Pernas', 'assets/exercises/Jump Squats.mp4'),
  ('Kettlebell Step Up', 'Subida no Step com Kettlebell', 'Pernas', 'assets/exercises/Kettlebell Step Up.mp4'),
  ('Machine Hack Squat', 'Agachamento Hack na Máquina', 'Pernas', 'assets/exercises/Machine Hack Squat.mp4'),
  ('Machine Leg Extension', 'Cadeira Extensora', 'Pernas', 'assets/exercises/Machine Leg Extension.mp4'),
  ('Machine Leg Press', 'Leg Press na Máquina', 'Pernas', 'assets/exercises/Machine Leg Press.mp4'),
  ('Machine Overhand Overhead Press', 'Desenvolvimento Pegada Pronada na Máquina', 'Ombros', 'assets/exercises/Machine Overhand Overhead Press.mp4'),
  ('Machine Pec Fly', 'Crucifixo na Máquina (Peck Deck)', 'Peito', 'assets/exercises/Machine Pec Fly.mp4'),
  ('Machine Seated Cable Row', 'Remada Sentado na Máquina', 'Costas', 'assets/exercises/Machine Seated Cable Row.mp4'),
  ('Neutral Chest Press', 'Supino Pegada Neutra na Máquina', 'Peito', 'assets/exercises/Neutral Chest Press.mp4'),
  ('Parallel Bar Dips', 'Mergulho nas Paralelas', 'Peito', 'assets/exercises/Parallel Bar Dips.mp4'),
  ('Plate Clean And Press', 'Clean and Press com Anilha', 'Corpo Inteiro', 'assets/exercises/Plate Clean And Press.mp4'),
  ('Plate Curl To Overhead Press', 'Rosca e Desenvolvimento com Anilha', 'Ombros', 'assets/exercises/Plate Curl To Overhead Press.mp4'),
  ('Plate Curl To Overhead Press To Tricep Extension', 'Rosca, Desenvolvimento e Tríceps com Anilha', 'Ombros', 'assets/exercises/Plate Curl To Overhead Press To Tricep Extension.mp4'),
  ('Plate Front Raise', 'Elevação Frontal com Anilha', 'Ombros', 'assets/exercises/Plate Front Raise.mp4'),
  ('Plate Full Lateral Raise', 'Elevação Lateral Completa com Anilha', 'Ombros', 'assets/exercises/Plate Full Lateral Raise.mp4'),
  ('Plate Halo', 'Halo com Anilha', 'Ombros', 'assets/exercises/Plate Halo.mp4'),
  ('Plate Lateral Raise', 'Elevação Lateral com Anilha', 'Ombros', 'assets/exercises/Plate Lateral Raise.mp4'),
  ('Plate Overhead Press To Tricep Extension', 'Desenvolvimento e Tríceps com Anilha', 'Ombros', 'assets/exercises/Plate Overhead Press To Tricep Extension.mp4'),
  ('Push Up', 'Flexão de Braço', 'Peito', 'assets/exercises/Push Up.mp4'),
  ('Barbell Bench Press', 'Supino Reto com Barra', 'Peito', 'assets/exercises/Barbell Bench Press.mp4');
